training:
  resume: False  # If True, must set hydra.run.dir accordingly
  pretrain_path: ""
  interval_visualize: 1000
  interval_save_checkpoint: 5000
  interval_delete_checkpoint: 10000
  interval_evaluate: 10000
  delete_all_checkpoints_after_training: False
  lr: 1e-4
  mixed_precision: True
  matmul_precision: high 
  max_iterations: 300000
  batch_size: 8
  num_workers: 8
  gpu_id: 0
  freeze_encoder: True
  seed: 0
  job_key: ""  # Use this for submitit sweeps where timestamps might collide
  translation_scale: 1.0
  regression: False
  load_extra_cameras: True
  calculate_intrinsics: False
  normalize_first_camera: False

model:
  pred_x0: True
  model_type: dit
  num_patches_x: 16
  num_patches_y: 16
  depth: 16
  num_images: 8
  random_num_images: True
  feature_extractor: dino
  append_ndc: True

noise_scheduler:
  type: linear
  max_timesteps: 100
  beta_start: 0.0001
  beta_end: 0.2

dataset:
  name: co3d
  category: "all_train"
  apply_augmentation: True

debug:
  wandb: True
  project_name: cameras_as_rays_github
  anomaly_detection: False

hydra:
  run:
    dir: ./output/${now:%m%d_%H%M%S_%f}${training.job_key}
  output_subdir: hydra
